# Generated by Django 2.2.6 on 2021-03-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=256, verbose_name='书名')),
                ('author', models.CharField(max_length=256, verbose_name='作者')),
                ('press', models.CharField(max_length=256, verbose_name='出版社')),
                ('borrow_status', models.BooleanField(verbose_name='借阅状态')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.CharField(max_length=12, verbose_name='工号')),
                ('manager_name', models.CharField(max_length=12, verbose_name='管理员姓名')),
                ('authority', models.SmallIntegerField(verbose_name='权限等级')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12, unique=True, verbose_name='学号')),
                ('student_name', models.CharField(max_length=12, verbose_name='姓名')),
                ('borrow_max', models.PositiveIntegerField(verbose_name='最大借阅数')),
                ('borrow_now', models.IntegerField(verbose_name='已借阅数')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '预约'), (1, '已借阅'), (2, '已归还')], default=0, verbose_name='借阅状态')),
                ('order_time', models.DateField(verbose_name='预约时间')),
                ('borrow_time', models.DateField(verbose_name='借阅时间')),
                ('giveback_time', models.DateField(verbose_name='归还时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Student')),
            ],
        ),
    ]
