# Generated by Django 2.2.6 on 2021-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_pwd',
            field=models.CharField(default=123, max_length=30, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='borrow_max',
            field=models.IntegerField(default=30, verbose_name='最大借阅数'),
        ),
        migrations.AlterField(
            model_name='student',
            name='borrow_now',
            field=models.IntegerField(default=0, verbose_name='已借阅数'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
