# Generated by Django 2.2.6 on 2021-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='student',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='管理权限'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='b0', max_length=256, verbose_name='书籍编号'),
        ),
    ]
